server:
  port: 8082
spring:
  application:
    name: cook
  zipkin:
    baseUrl: http://127.0.0.1:9411/
    enabled: true
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
#tracking:
#  zipkin:
#    enabled: true
logging:
  level:
    root: DEBUG